# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sanity

on: [push, pull_request]

jobs:
  test:
    
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - name: Set up pipenv
      uses: dschep/install-pipenv-action@v1
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies and quizmake
      run: |
        python -m pip install --upgrade pip
        pipenv install --deploy --dev
    
    - name: Sort imports 
      run: |
        pipenv run isort --recursive --diff
    
    - name: Static type checking
      run: |
        pipenv run mypy
    
    - name: Check code using black
      run: |
        pipenv run black --check .

    - name: Check code using flake8
      run: |
        pipenv run flake8 . --count --show-source --statistics
    
    - name: Check code using pylint
      run: |
        pipenv run pylint quizmake
        pipenv run pylint tests/*/*.py

    - name: Smoke tests
      run: |
        pipenv run pytest tests/smoke_tests/
        
    - name: End-to-End tests
      run: |
        pipenv run pytest tests/end_to_end_tests/

    - name: Integration tests
      run: |
        pipenv run pytest tests/integration_tests/

    - name: Regression tests
      run: |
        pipenv run pytest tests/regression_tests/
    
    - name: Unit tests
      run: |
        pipenv run pytest tests/unit_tests/
