# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sanity

on: [push, pull_request]

jobs:
  test:
    
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - name: Set up pipenv
      uses: dschep/install-pipenv-action@v1
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies and quizmake
      run: |
        python -m pip install --upgrade pip
        pipenv install --deploy --dev --python 3.8

    - name: Smoke tests
      run: |
        pipenv run pytest --cov=quizmake --cov-report term-missing tests/smoke_tests/
        
    - name: End-to-End tests
      run: |
        pipenv run pytest --cov=quizmake --cov-report term-missing tests/end_to_end_tests/

    - name: Integration tests
      run: |
        pipenv run pytest --cov=quizmake --cov-report term-missing tests/integration_tests/

    - name: Regression tests
      run: |
        pipenv run pytest --cov=quizmake --cov-report term-missing tests/regression_tests/
    
    - name: Unit tests
      run: |
        pipenv run pytest --cov=quizmake --cov-report term-missing tests/unit_tests/
