# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lintest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies and quizmake
      run: |
        python -m pip install --upgrade pip
        pipenv install --deploy --dev
    
    - name: Housekeeping
      run: |
        pipenv run isort --recursive --diff
        pipenv run black --check .
        pipenv run flake8 . --count --show-source --statistics
        pipenv run mypy
        pipenv run pytest tests/
